# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1067, 764)
        Dialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.18408 rgba(131, 73, 255, 255), stop:1 rgba(163, 151, 255, 255))\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 90, 1071, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 160, 1071, 31))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(150, 280, 320, 300))
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"border-image:url(\"mask.jpg\");\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"border-style:solid;\n"
"border-width:4px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color:rgba(128,128,128,200 );\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 280, 320, 300))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"border-image:url(\"social.jpg\");\n"
"border-radius:10px;\n"
"border-width:1px;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"border-style:solid;\n"
"border-width:4px;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 640, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"background-color:rgba(255,255,255,255);\n"
"color:rgba(0,0,0,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(255,254,247,100);\n"
"background-position:calc(100% -5px)center;\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"background-color:rgba(255,254,247,200 );\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(570, 640, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{\n"
"background-color:rgba(255,255,255,255);\n"
"color:rgba(0,0,0,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_4:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(50,50,50,100);\n"
"background-position:calc(100% -5px)center;\n"
"}\n"
"QPushButton#pushButton_4:hover{\n"
"background-color:rgba(255,254,247,200);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome"))
        self.label_2.setText(_translate("Dialog", "Sign In or Create a new Account"))
        self.pushButton_3.setText(_translate("Dialog", "SignUp"))
        self.pushButton_4.setText(_translate("Dialog", "Login"))


